using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StructureGate;

/// <summary>
/// WHAT A C# SYNTAX NODE MEANS, for the rows of <see cref="CsRows"/> — the name it is written as, what it
/// touches, and the shape it has. Nothing here is about a table or a database.
///
/// THE FACTS ARE EXTRACTED, THE TEXT IS CARRIED. Every row keeps its own `source` so a reader can see the
/// code, and beside it what was already read off that code: what it reads, what it calls, which strings it
/// spells out. A consumer that pattern-matches over `source` has re-implemented, badly, what this pass
/// already resolved — and it would be re-implementing it with a regex over C#, which is the thing this
/// whole tool exists to refuse.
///
/// IT ANSWERS THE SAME QUESTIONS THE PYTHON HALF DOES, in the same columns, because both halves write the
/// same tables: a query written against `reads` has to mean the same thing whichever language the row came
/// from. Where the two languages genuinely differ the C# answer is the one this file states in a comment.
/// </summary>
internal static class CsFacts
{
    /// <summary>How deep the structural skeleton of an expression goes. The shape is for recognising a
    /// pattern; the code itself is in `source`, in full, in the same row.</summary>
    private const int MaxDepth = 4;

    /// <summary>Children kept at each level of the shape. A long argument list says nothing more about the
    /// shape after the first few.</summary>
    private const int MaxChildren = 8;

    /// <summary>The names generators write when they leave no marker inside the file.</summary>
    private static readonly string[] GeneratedNames = [".designer.cs", ".g.cs", ".generated.cs"];

    /// <summary>
    /// Whether this file was WRITTEN BY A TOOL. Read off the marker the generator itself put there — the
    /// `&lt;auto-generated&gt;` comment every one of them writes — and off the names the tooling uses when
    /// it writes no marker. NOT guessed from a folder called `Migrations`: a folder name is a convention,
    /// and a file somebody hand-wrote into it is still hand-written.
    ///
    /// BOTH HALVES ASK THIS ONE QUESTION. The deep map skips a generated file's rows entirely; the
    /// file-level map still reads what it declares and uses — an NSwag client IS referenced by hand-written
    /// code and an edge to it is real — but does not FINGERPRINT it, because "this generated file is a copy
    /// of that generated file" is a finding nobody can act on and it is most of what the detector reports.
    /// </summary>
    public static bool Generated(SyntaxNode root, string rel)
    {
        foreach (var name in GeneratedNames)
        {
            if (rel.EndsWith(name, StringComparison.OrdinalIgnoreCase)) return true;
        }
        foreach (var trivia in root.GetLeadingTrivia())
        {
            if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
                && !trivia.IsKind(SyntaxKind.MultiLineCommentTrivia)) continue;
            if (trivia.ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) return true;
        }
        return false;
    }

    /// <summary>What a sub-tree READS, CALLS and SPELLS OUT.</summary>
    public sealed record Touched(List<string> Reads, List<string> Calls, List<string> Strings);

    /// <summary>
    /// <c>a.b.c</c> for a name written out, "" for anything computed — an indexer, a call in the middle of
    /// the chain, a parenthesised receiver.
    ///
    /// READ OFF THE TREE AND NEVER OFF THE TEXT, so a chain written across three lines reads the same as
    /// one written on a single line, and a `[0]` in the middle of it yields "" instead of a guess.
    ///
    /// `this.` IS DROPPED, because `this.count` and `count` are the same name and a query for one has to
    /// find the other. `base.` is KEPT: it names a different member.
    /// </summary>
    public static string Dotted(SyntaxNode? node)
    {
        var parts = new List<string>();
        while (true)
        {
            switch (node)
            {
                case MemberAccessExpressionSyntax access:
                    parts.Add(access.Name.Identifier.ValueText);
                    node = access.Expression;
                    continue;
                case MemberBindingExpressionSyntax binding:
                    // `x?.y` — the receiver hangs off the conditional access above, so this is as far as
                    // the written name goes.
                    parts.Add(binding.Name.Identifier.ValueText);
                    return Join(parts);
                case QualifiedNameSyntax qualified:
                    parts.Add(qualified.Right.Identifier.ValueText);
                    node = qualified.Left;
                    continue;
                case AliasQualifiedNameSyntax alias:
                    parts.Add(alias.Name.Identifier.ValueText);
                    parts.Add(alias.Alias.Identifier.ValueText);
                    return Join(parts);
                case IdentifierNameSyntax name:
                    parts.Add(name.Identifier.ValueText);
                    return Join(parts);
                case GenericNameSyntax generic:
                    parts.Add(generic.Identifier.ValueText);
                    return Join(parts);
                case PredefinedTypeSyntax predefined:
                    parts.Add(predefined.Keyword.ValueText);
                    return Join(parts);
                case ThisExpressionSyntax:
                    return Join(parts);
                case BaseExpressionSyntax:
                    parts.Add("base");
                    return Join(parts);
                default:
                    return "";
            }
        }
    }

    private static string Join(List<string> parts)
    {
        if (parts.Count == 0) return "";
        parts.Reverse();
        return string.Join(".", parts);
    }

    /// <summary>
    /// What a sub-tree touches, so a query never has to look at `source` again.
    ///
    /// EVERY PREFIX OF A CHAIN IS A READ — `STORE.artifact(name)` reads `STORE` and `STORE.artifact` — which
    /// is what makes "who reads this constant" answerable without knowing how it was reached. That is the
    /// python half's rule too, and the two tables are queried together.
    /// </summary>
    public static Touched Of(SyntaxNode? node)
    {
        var reads = new SortedSet<string>(StringComparer.Ordinal);
        var calls = new SortedSet<string>(StringComparer.Ordinal);
        var strings = new List<string>();
        if (node is null) return new Touched([], [], []);

        foreach (var sub in node.DescendantNodesAndSelf())
        {
            switch (sub)
            {
                case IdentifierNameSyntax name when !IsTail(name):
                    reads.Add(name.Identifier.ValueText);
                    break;
                case MemberAccessExpressionSyntax or MemberBindingExpressionSyntax:
                    var written = Dotted(sub);
                    if (written.Length > 0) reads.Add(written);
                    break;
                case InvocationExpressionSyntax call:
                    var callee = Dotted(call.Expression);
                    if (callee.Length > 0) calls.Add(callee);
                    break;
                case BaseObjectCreationExpressionSyntax creation:
                    // `new Reader()` is a call OF `Reader` in the python half's vocabulary, where a class is
                    // called to construct it. A row that said `new` instead would join to nothing.
                    var type = creation is ObjectCreationExpressionSyntax named ? Dotted(named.Type) : "";
                    if (type.Length > 0) calls.Add(type);
                    break;
                case LiteralExpressionSyntax { Token.Value: string spelled } when spelled.Length > 0:
                    strings.Add(spelled);
                    break;
            }
        }
        return new Touched([.. reads], [.. calls], strings);
    }

    /// <summary>The `b` of `a.b` — the MEMBER half of a written name, already carried by the chain's own
    /// dotted form. Counted on its own it would report a read of every method name in the file.</summary>
    public static bool IsTail(SimpleNameSyntax name) => name.Parent switch
    {
        MemberAccessExpressionSyntax access => access.Name == name,
        QualifiedNameSyntax qualified => qualified.Right == name,
        MemberBindingExpressionSyntax binding => binding.Name == name,
        NameColonSyntax or NameEqualsSyntax => true,
        _ => false,
    };

    /// <summary>The structural skeleton of an expression: kinds only, no names, capped.</summary>
    public static string Shape(SyntaxNode node)
    {
        var buffer = new MemoryStream();
        using (var json = new Utf8JsonWriter(buffer))
        {
            Skeleton(json, node, 0);
        }
        return Encoding.UTF8.GetString(buffer.ToArray());
    }

    private static void Skeleton(Utf8JsonWriter json, SyntaxNode node, int depth)
    {
        json.WriteStartObject();
        // THE KIND, NOT THE TYPE NAME. Every operator in C# is a `BinaryExpressionSyntax`, so a shape built
        // from type names would fingerprint `a + b` and `a == b` alike and the table would group two
        // expressions that share nothing.
        json.WriteString("k", node.Kind().ToString());
        var kids = node.ChildNodes().OfType<ExpressionSyntax>().Take(MaxChildren).ToList();
        if (depth < MaxDepth && kids.Count > 0)
        {
            json.WriteStartArray("c");
            foreach (var kid in kids) Skeleton(json, kid, depth + 1);
            json.WriteEndArray();
        }
        json.WriteEndObject();
    }

    /// <summary>The source text of a node, IN FULL. Trivia inside the span is kept — a comment written into
    /// the middle of an expression is part of what is there. NOTHING IS CUT: a call cut at 400 characters with
    /// no marker read as the whole call, and a reader acted on the half it was shown.</summary>
    public static string Text(SyntaxNode? node) => node is null ? "" : node.ToString().Trim();

    /// <summary>The first line of a doc comment's `&lt;summary&gt;`, or "". A member's intent is written
    /// there the way a python function's is written in its docstring, and the `doc` column holds both.</summary>
    public static string Doc(SyntaxNode node)
    {
        foreach (var trivia in node.GetLeadingTrivia())
        {
            if (trivia.GetStructure() is not DocumentationCommentTriviaSyntax comment) continue;
            foreach (var element in comment.Content.OfType<XmlElementSyntax>())
            {
                if (element.StartTag.Name.LocalName.ValueText != "summary") continue;
                var text = new StringBuilder();
                foreach (var raw in element.Content.ToFullString().Split('\n'))
                {
                    var line = raw.Trim();
                    if (line.StartsWith("///", StringComparison.Ordinal)) line = line[3..].Trim();
                    if (line.Length == 0) continue;
                    if (text.Length > 0) text.Append(' ');
                    text.Append(line);
                }
                if (text.Length > 0) return text.ToString();
            }
        }
        return "";
    }
}
