using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StructureGate;

/// <summary>
/// THE DEEP C# HALF: every declaration, call, branch, assignment and expression of one file as a ROW.
///
/// TWO GRANULARITIES, ON PURPOSE. <see cref="CSharpMap"/> beside this answers questions about FILES — what
/// references what, what is written twice, what nothing reads — and it carries no code at all, because a
/// copy of the source in a JSON file is a copy that drifts. That leaves a whole class of question
/// unaskable: which calls pass a flag, what reads this constant, where is this route string built. Those
/// are about EXPRESSIONS, and a file-level graph has none.
///
/// THE SAME TABLES AS THE PYTHON HALF, deliberately. `classes`, `functions`, `calls`, `expressions` and the
/// rest mean the same thing whichever language filled them, so one query answers over a repo that is half
/// C# and half python — which is what the trees this runs on actually look like. Where C# has something
/// python does not, it arrives as an extra COLUMN (a `using static` has a `kind`) rather than as a table of
/// its own; the database widens a table to fit it.
///
/// SCOPE IS RECORDED, NOT INFERRED. A row says which type and which member it sits in, because "which calls
/// happen inside `Resolve`" is the question people actually have, and recovering that from line numbers
/// afterwards means re-deriving what the tree already knew.
///
/// A PARSE ERROR IS NOT REPORTED HERE. Roslyn error-recovers into a partial tree and <see cref="CSharpMap"/>
/// already names that file, off the same parse, in the same run — a second message would be the same defect
/// counted twice.
/// </summary>
internal sealed partial class CsRows : CSharpSyntaxWalker
{
    private readonly CsTables rows;
    private readonly SyntaxTree tree;
    private readonly SemanticModel? model;
    private readonly string file;
    private readonly List<(string Kind, string Name)> stack = [];
    private string space = "";

    private CsRows(CsTables rows, SyntaxTree tree, SemanticModel? model, string file)
    {
        this.rows = rows;
        this.tree = tree;
        this.model = model;
        this.file = file;
    }

    /// <summary>
    /// One file, as rows. The sha is handed in rather than computed here: the caller already hashed the
    /// tree to decide which files moved, and hashing it twice is how two answers to one question start.
    ///
    /// THE TREE AND THE MODEL COME FROM THE CALLER when the file belongs to a project that bound — a model
    /// only answers about the tree its own compilation holds, so parsing a second copy here would produce a
    /// tree the model rejects. Both may be absent, and then this is the syntax pass it always was.
    /// </summary>
    public static void Read(CsTables rows, string rel, string text, string sha,
        SyntaxTree? parsed = null, SemanticModel? model = null, string project = "", bool compiled = true,
        CsRazor.Output? razor = null, bool excluded = false, IReadOnlyList<Diagnostic>? declared = null,
        IReadOnlyDictionary<string, string>? rels = null)
    {
        // MARKUP IS READ AS THE TREE THE RAZOR COMPILER WROTE FOR IT - see CsRazor. Without one there is no C#
        // to read, and parsing the markup as C# would be rows about text that is not code.
        var markup = CsRazor.Owns(rel);
        if (markup && parsed is null)
        {
            rows.Add("files", "f", ("path", rel), ("sha", sha), ("lines", text.Split('\n').Length), ("project", project),
                ("semantic", 0), ("generated", 0), ("compiled", 0), ("errors", 0), ("razor", ""));
            return;
        }
        var tree = parsed ?? CSharpSyntaxTree.ParseText(text);
        var root = (CompilationUnitSyntax)tree.GetRoot();
        // A RAZOR TREE STARTS `// <auto-generated/>`, and it is still the file somebody wrote.
        var generated = !markup && CsFacts.Generated(root, rel);
        var space = root.DescendantNodes().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault();
        var file = rows.Add("files", "f",
            ("path", rel),
            // The MODULE a reader would name this file by: its namespace where it has one, its own name
            // where it does not. The python half fills the same column with the module name.
            ("module", space is not null ? space.Name.ToString() : Path.GetFileNameWithoutExtension(rel)),
            ("sha", sha),
            ("lines", text.Split('\n').Length),
            ("entry", Entry(root) ? 1 : 0),
            ("doc", Headline(root)),
            // WHICH PROJECT COMPILES THIS FILE, and whether it was BOUND. A reader cannot otherwise tell a
            // name that resolves to nothing from a file nothing was ever resolved for: both leave the
            // semantic columns empty, and only one of them is a fact about the code.
            ("project", project),
            ("semantic", model is not null ? 1 : 0),
            ("generated", generated ? 1 : 0),
            // A FILE THE PROJECT DOES NOT COMPILE is listed and not walked, for the same reason a generated
            // one is: dropping it would make it look like a file the tree does not have, and mapping it
            // would report rows for code that is in no assembly.
            ("compiled", compiled ? 1 : 0),
            ("errors", 0),
            ("razor", razor?.Kind ?? ""),
            // `--map-exclude` MATCHED IT: the consumer asked for no rows of this file. It is still compiled, so
            // everything else binds against it; its own bodies are never bound, which is the whole saving.
            ("excluded", excluded ? 1 : 0));

        if (!compiled || excluded) return;

        var unneeded = model is not null ? Diagnostics(rows, model, declared ?? [], file, markup) : null;

        // A GENERATED FILE IS LISTED, NOT WALKED. Nobody asks which function reads a constant inside an EF
        // model snapshot, and the rows are not free: on a real tree, most of the
        // expression rows came from `.Designer.cs` files, and writing them was slow. The file row
        // stays, and says why it has no rows of its own — a file that simply vanished would read as a file
        // the map never saw.
        if (generated) return;

        var walker = new CsRows(rows, tree, model, file) { space = space is not null ? space.Name.ToString() : "", razor = markup,
            rels = model is null ? null : rels, unneeded = markup ? null : unneeded };
        // EVERY ROW OF A WALKED FILE IS WRITTEN - there is no per-file budget. One cut a file off at 20 000
        // rows and marked it `capped`, and the rows past the cut were code nobody could ask about. What
        // keeps build output out is the GENERATED rule above, and a file it misses is still source.
        walker.Visit(root);
        if (!markup) walker.Comments(root);
        foreach (var target in walker.reached) rows.Add("file_refs", "fr", ("file", file), ("target", target));
        if (razor is not null) Renders(rows, file, walker.space, rel, razor);
    }

    /// <summary>
    /// WHAT THE COMPILER SAYS IS WRONG WITH THIS FILE — errors only, every one a row, counted in full.
    ///
    /// This map builds its own compilation from what restore and build left on disk, so an error here is
    /// usually not a bug in the code: it is a reference this pass could not find, a file the `.csproj`
    /// excludes, a type a source generator was going to write. That is exactly why the rows exist. A reader
    /// looking at an unresolved `symbol` column is otherwise left guessing whether the name resolves to
    /// nothing or whether this file never bound properly at all, and `files.errors` answers it with a number.
    ///
    /// THE THREE STAGES IN ROSLYN'S OWN ORDER - syntax, declarations, method bodies - with the declarations
    /// asked once per compilation (<paramref name="declared"/>, see `CsModels`), not once per file.
    /// </summary>
    private static readonly string[] GeneratorIds = ["CS8795", "CS0762"];

    /// <summary>How many `generator` diagnostics this run recorded - said once, with what to set.</summary>
    internal static int GeneratorGaps;

    /// <returns>Where each `using` the compiler calls unnecessary (CS8019, hidden) starts - or null when the file has an
    /// error, since a `using` whose types did not resolve is not "unused".</returns>
    private static HashSet<int>? Diagnostics(CsTables rows, SemanticModel model, IReadOnlyList<Diagnostic> declared, string file, bool markup)
    {
        var errors = 0;
        var unneeded = new HashSet<int>();
        foreach (var diagnostic in model.GetSyntaxDiagnostics().Concat(declared).Concat(model.GetMethodBodyDiagnostics()))
        {
            if (diagnostic.Id == "CS8019") unneeded.Add(diagnostic.Location.SourceSpan.Start);
            if (diagnostic.Severity != DiagnosticSeverity.Error) continue;
            // IN MARKUP ONLY WHAT WAS WRITTEN COUNTS: an error in the hidden plumbing (an MVC base a RazorEngine
            // template does not have) is the generator's, and the expressions around it still bind.
            if (markup && model.SyntaxTree.GetLineVisibility(diagnostic.Location.SourceSpan.Start) != LineVisibility.Visible) continue;
            // NOR A NAME THE GENERATOR CALLS that the template's base does not have: RazorEngine's base has no MVC
            // `WriteAttributeValue`, so such a template would "fail" over it while every expression in it bound.
            if (markup && IsPlumbingName(model.SyntaxTree.GetRoot().FindNode(diagnostic.Location.SourceSpan).ToString())) continue;
            // A PARTIAL WITH NO IMPLEMENTATION is a source generator's missing output (Mapperly's `[Mapper]`): the
            // declaration binds, only the body is not there. Labelled, and not an error of the file.
            var generator = GeneratorIds.Contains(diagnostic.Id);
            if (generator) GeneratorGaps++;
            else errors++;
            var line = diagnostic.Location.GetMappedLineSpan().StartLinePosition.Line + 1;
            rows.Add("diagnostics", "dg",
                ("file", file),
                ("cls", ""),
                ("func", ""),
                ("line", line),
                ("name", diagnostic.Id),
                ("kind", generator ? "generator" : "error"),
                ("source", diagnostic.GetMessage()));
        }
        if (errors > 0) rows.Count(file, errors);
        return errors > 0 ? null : unneeded;
    }

    /// <summary>Top-level statements, or a `Main`. Having no reader is normal for one of these.</summary>
    private static bool Entry(CompilationUnitSyntax root) =>
        root.Members.OfType<GlobalStatementSyntax>().Any()
        || root.DescendantNodes().OfType<MethodDeclarationSyntax>()
            .Any(m => m.Identifier.ValueText == "Main");

    private static string Headline(CompilationUnitSyntax root)
    {
        foreach (var member in root.DescendantNodes().OfType<MemberDeclarationSyntax>())
        {
            var doc = CsFacts.Doc(member);
            if (doc.Length > 0) return doc;
        }
        return "";
    }

    private int Line(SyntaxNode node) => razor ? Mapped(node, end: false) : tree.GetLineSpan(node.Span).StartLinePosition.Line + 1;

    private int EndLine(SyntaxNode node) => razor ? Mapped(node, end: true) : tree.GetLineSpan(node.Span).EndLinePosition.Line + 1;

    /// <summary>The type this row sits in — the OUTERMOST one, so a nested helper class still answers
    /// "which type is this in" with the type a reader would name.</summary>
    private string Cls() => stack.FirstOrDefault(s => s.Kind == "class").Name ?? "";

    private string Func()
    {
        for (var i = stack.Count - 1; i >= 0; i--)
        {
            if (stack[i].Kind == "func") return stack[i].Name;
        }
        return "";
    }

    /// <summary>
    /// The name a C# reader would write to reach this member from anywhere: namespace, enclosing types,
    /// member. The python half's qualname stops at the module because python's own `__qualname__` does;
    /// C# has no such boundary, and a `qualname` that dropped the namespace would collide across two
    /// `Program` classes in one tree.
    /// </summary>
    private string Qualified(string name)
    {
        var parts = new List<string>();
        if (space.Length > 0) parts.Add(space);
        parts.AddRange(stack.Select(s => s.Name));
        parts.Add(name);
        return string.Join(".", parts);
    }

    /// <summary>Every row carries where it sits. Named once, because a row that filled these in itself
    /// would be a second definition of "which scope am I in".</summary>
    private (string Key, object Value)[] Where() => currentCase is null ? [("file", file), ("cls", Cls()), ("func", Func())] : [("file", file), ("cls", Cls()), ("func", Func()), ("case", currentCase)];

    /// <summary>One row, with where it sits.</summary>
    private string Row(string table, string prefix, params (string Key, object Value)[] cells) =>
        razor && cells.Any(c => c.Key == "line" && c.Value is 0) ? "" : rows.Add(table, prefix, [.. Where(), .. cells]);

    // ---- declarations -------------------------------------------------------------------------------

    public override void VisitUsingDirective(UsingDirectiveSyntax node)
    {
        // A `using` IS the import row of this language, and the three ways of writing one are told apart by
        // `kind` rather than by three tables: `using static` brings in members, an alias renames, a global
        // one applies to files that never mention it.
        var kind = node.GlobalKeyword.ValueText.Length > 0 ? "global"
            : node.StaticKeyword.ValueText.Length > 0 ? "static"
            : node.Alias is not null ? "alias"
            : "using";
        var cells = new List<(string Key, object Value)>
        {
            ("line", Line(node)),
            ("module", node.Name?.ToString() ?? ""),
            ("name", ""),
            ("alias", node.Alias?.Name.Identifier.ValueText ?? ""),
            ("kind", kind),
            ("level", 0),
            // A `using` cannot be conditional in C#, so nothing here is ever optional — the column exists
            // because the python half fills it and the two are queried together.
            ("guarded", 0),
        };
        // WHETHER ANYTHING IN THE FILE NEEDS IT, as the compiler says (CS8019) - left out where it cannot say: no model,
        // markup, a file with errors, a `global using` (it serves files that never mention it). Without it
        // `--unused-imports` read every C# `using` as unused.
        if (unneeded is not null && kind != "global") cells.Add(("used", unneeded.Contains(node.SpanStart) ? 0 : 1));
        Row("imports", "i", [.. cells]);
        base.VisitUsingDirective(node);
    }

    public override void VisitClassDeclaration(ClassDeclarationSyntax node) => Type(node, "class", node.BaseList, () => base.VisitClassDeclaration(node));

    public override void VisitStructDeclaration(StructDeclarationSyntax node) => Type(node, "struct", node.BaseList, () => base.VisitStructDeclaration(node));

    public override void VisitInterfaceDeclaration(InterfaceDeclarationSyntax node) => Type(node, "interface", node.BaseList, () => base.VisitInterfaceDeclaration(node));

    public override void VisitRecordDeclaration(RecordDeclarationSyntax node) => Type(node, "record", node.BaseList, () => base.VisitRecordDeclaration(node));

    public override void VisitEnumDeclaration(EnumDeclarationSyntax node) => Type(node, "enum", node.BaseList, () => { Enum(node); base.VisitEnumDeclaration(node); });

    public override void VisitDelegateDeclaration(DelegateDeclarationSyntax node)
    {
        // A delegate declares a TYPE another file can name, so it belongs in `classes` beside the rest; its
        // signature is recorded the way a function's is.
        Declared(node, node.Identifier.ValueText, "delegate", node.Modifiers);
        Row("classes", "c",
            ("line", Line(node)), ("name", node.Identifier.ValueText),
            ("qualname", Qualified(node.Identifier.ValueText)), ("kind", "delegate"),
            ("bases", new List<string>()), ("doc", CsFacts.Doc(node)));
        Parameters(node.ParameterList, node.Identifier.ValueText);
        base.VisitDelegateDeclaration(node);
    }

    private void Type(BaseTypeDeclarationSyntax node, string kind, BaseListSyntax? bases, Action descend)
    {
        var name = node.Identifier.ValueText;
        Declared(node, name, kind, node.Modifiers);
        Row("classes", "c",
            ("line", Line(node)),
            ("name", name),
            ("qualname", Qualified(name)),
            ("kind", kind),
            ("bases", bases is null ? [] : bases.Types.Select(t => Resolved(t.Type)).ToList()),
            // The type as the COMPILER names it. Two `Program` classes in one solution are one string in
            // the source and two symbols here, and a base list resolved the same way says which `Controller`.
            ("symbol", CsSemantics.DeclaredName(model, node)),
            ("doc", CsFacts.Doc(node)));
        Attributes(node.AttributeLists, name, kind);
        stack.Add(("class", name));
        descend();
        stack.RemoveAt(stack.Count - 1);
    }

    public override void VisitMethodDeclaration(MethodDeclarationSyntax node) =>
        Function(node, node.Identifier.ValueText, "method", node.Modifiers, node.ParameterList,
            node.ReturnType.ToString(), () => base.VisitMethodDeclaration(node));

    public override void VisitConstructorDeclaration(ConstructorDeclarationSyntax node) =>
        Function(node, node.Identifier.ValueText, "constructor", node.Modifiers, node.ParameterList,
            "", () => base.VisitConstructorDeclaration(node));

    public override void VisitDestructorDeclaration(DestructorDeclarationSyntax node) =>
        Function(node, "~" + node.Identifier.ValueText, "destructor", node.Modifiers, node.ParameterList,
            "", () => base.VisitDestructorDeclaration(node));

    public override void VisitOperatorDeclaration(OperatorDeclarationSyntax node) =>
        Function(node, "operator " + node.OperatorToken.ValueText, "operator", node.Modifiers,
            node.ParameterList, node.ReturnType.ToString(), () => base.VisitOperatorDeclaration(node));

    public override void VisitConversionOperatorDeclaration(ConversionOperatorDeclarationSyntax node) =>
        Function(node, "operator " + node.Type, "operator", node.Modifiers, node.ParameterList,
            node.Type.ToString(), () => base.VisitConversionOperatorDeclaration(node));

    public override void VisitLocalFunctionStatement(LocalFunctionStatementSyntax node) =>
        Function(node, node.Identifier.ValueText, "local", node.Modifiers, node.ParameterList,
            node.ReturnType.ToString(), () => base.VisitLocalFunctionStatement(node));

    public override void VisitPropertyDeclaration(PropertyDeclarationSyntax node)
    {
        // A PROPERTY IS A MEMBER, NOT A FIELD. Its accessors get rows of their own below, but a query for
        // "what does this type expose" has to find the property itself — and an auto-property has no
        // accessor body to stand in for it.
        Function(node, node.Identifier.ValueText, "property", node.Modifiers, null,
            node.Type.ToString(), () => base.VisitPropertyDeclaration(node));
    }

    /// <summary>
    /// A FIELD IS A MEMBER, and everything its initializer builds sits INSIDE it.
    ///
    /// Without the scope, every row of every field initializer in a type carries the same empty member
    /// name, and several fields of one class become indistinguishable: a reader looking for "the id array
    /// this creation iterates" finds the first array in the CLASS. Measured on a real tree — with
    /// fields `_a`, `_b` and `_c`, an entry built
    /// by the last came out attached to the first field's id instead of to the
    /// items that field actually iterates.
    /// </summary>
    public override void VisitFieldDeclaration(FieldDeclarationSyntax node)
    {
        // The rows ABOUT the field — its consts, its assignment — belong to the scope the field is in.
        Field(node);
        // The FIRST declarator names the member: `int a = 1, b = 2;` is one field declaration to C#, and a
        // row inside either initializer belongs to the same declaration.
        var name = node.Declaration.Variables.FirstOrDefault()?.Identifier.ValueText ?? "";
        if (name.Length > 0) stack.Add(("func", name));
        base.VisitFieldDeclaration(node);
        if (name.Length > 0) stack.RemoveAt(stack.Count - 1);
    }

    public override void VisitIndexerDeclaration(IndexerDeclarationSyntax node) =>
        Function(node, "this[]", "indexer", node.Modifiers, node.ParameterList, node.Type.ToString(),
            () => base.VisitIndexerDeclaration(node));

    public override void VisitAccessorDeclaration(AccessorDeclarationSyntax node)
    {
        // NAMED FOR WHAT IT IS PART OF. `get` on its own is the name of every accessor in the tree, and a
        // `functions` row nothing can tell apart from another is a row nobody can join to.
        var owner = Func();
        var name = owner.Length > 0 ? $"{owner}.{node.Keyword.ValueText}" : node.Keyword.ValueText;
        Function(node, name, "accessor", node.Modifiers, null, "", () => base.VisitAccessorDeclaration(node));
    }

    private void Function(SyntaxNode node, string name, string kind, SyntaxTokenList modifiers,
        BaseParameterListSyntax? parameters, string returns, Action descend)
    {
        Row("functions", "fn",
            ("line", Line(node)),
            ("name", name),
            ("qualname", Qualified(name)),
            ("kind", kind),
            ("args", parameters is null ? [] : parameters.Parameters.Select(p => p.Identifier.ValueText).ToList()),
            ("returns", returns),
            ("symbol", CsSemantics.DeclaredName(model, node)),
            // The return type RESOLVED: `var`-shaped source, an alias, a type from another project — the
            // text says one thing per file and this says the same thing everywhere.
            ("type", CsSemantics.Declared(model, node)),
            ("is_async", modifiers.Any(m => m.IsKind(SyntaxKind.AsyncKeyword)) ? 1 : 0),
            ("doc", CsFacts.Doc(node)),
            ("end_line", EndLine(node)));
        Attributes(AttributesOf(node), name, kind);
        Parameters(parameters, name);
        stack.Add(("func", name));
        descend();
        stack.RemoveAt(stack.Count - 1);
    }

    private static SyntaxList<AttributeListSyntax> AttributesOf(SyntaxNode node) => node switch
    {
        MemberDeclarationSyntax member => member.AttributeLists,
        LocalFunctionStatementSyntax local => local.AttributeLists,
        _ => default,
    };

    /// <summary>
    /// One row per parameter, with its type and its DEFAULT EXPRESSION.
    ///
    /// `functions.args` carries the NAMES only, and a name says nothing about what a signature reads. A
    /// default that names a constant — `int size = Limits.Page` — is a read of that constant, and without
    /// this row it is a read nothing records, so the constant looks dead.
    /// </summary>
    private void Parameters(BaseParameterListSyntax? parameters, string owner)
    {
        if (parameters is null) return;
        var position = 0;
        foreach (var parameter in parameters.Parameters)
        {
            var modifier = parameter.Modifiers.FirstOrDefault(m => !m.IsKind(SyntaxKind.None));
            Row("parameters", "p",
                ("line", Line(parameter)),
                ("func", owner),
                ("qualname", Qualified(owner)),
                ("position", position++),
                ("name", parameter.Identifier.ValueText),
                // The python half's `kind` says how a parameter may be passed; C#'s says the same thing in
                // its own vocabulary — `ref`, `out`, `params`, `this`.
                ("kind", modifier.ValueText.Length > 0 ? modifier.ValueText : "positional"),
                ("annotation", parameter.Type?.ToString() ?? ""),
                ("type", parameter.Type is null ? "" : CsSemantics.Type(model, parameter.Type)),
                ("default_expr", CsFacts.Text(parameter.Default?.Value)),
                ("reads", CsFacts.Of(parameter.Default?.Value).Reads));
            Attributes(parameter.AttributeLists, parameter.Identifier.ValueText, "parameter");
        }
    }

    /// <summary>
    /// An ATTRIBUTE is this language's decorator: a declaration handed to something else at load time, which
    /// is how a type nothing calls is still reached. `[Route("api/x")]` and `@app.get("/x")` are the same
    /// fact about a codebase, so they land in the same table.
    /// </summary>
    private void Attributes(SyntaxList<AttributeListSyntax> lists, string target, string targetKind)
    {
        foreach (var attribute in lists.SelectMany(l => l.Attributes))
        {
            var bound = CsSemantics.Bound(model, attribute);
            Row("decorators", "d",
                ("line", Line(attribute)),
                ("name", CsFacts.Dotted(attribute.Name) is { Length: > 0 } written ? written : attribute.Name.ToString()),
                ("target", target),
                ("target_kind", targetKind),
                // `[Route]` and `[RouteAttribute]` are the same attribute, and two `[Feature]` in two
                // namespaces are not. Only the symbol tells either of those apart.
                ("symbol", CsSemantics.Name(bound)),
                ("source", CsFacts.Text(attribute)));
            RegexAttribute(attribute, bound, target);
        }
    }

    /// <summary>A base type as the compiler resolves it, or as it is written when nothing bound.</summary>
    private string Resolved(TypeSyntax type)
    {
        var symbol = CsSemantics.Name(CsSemantics.Bound(model, type));
        if (symbol.Length > 0) return symbol;
        return CsFacts.Dotted(type) is { Length: > 0 } written ? written : type.ToString();
    }

    /// <summary>
    /// What this file offers another one. The python half fills `exports` from `__all__`, which is the same
    /// statement made explicitly; C# states it with a modifier, so it is read off the modifier.
    /// </summary>
    private void Declared(SyntaxNode node, string name, string kind, SyntaxTokenList modifiers)
    {
        if (!modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword))) return;
        Row("exports", "e", ("line", Line(node)), ("name", name), ("kind", kind));
    }
}
