<#
    WHAT A SOURCE GENERATOR WROTE. A generator cannot run inside this exe - NativeAOT loads no analyzer - so a
    Mapperly `[Mapper]` partial had no body and every one was a compile error. What the generator wrote to disk
    (`<EmitCompilerGeneratedFiles>`) is now compiled, and what it did not write is labelled `generator`, not an error.

    Its helpers are its own - `-Only CsGenerated` runs this suite alone.
#>

$script:CsGeneratedProject = '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework>' +
    '<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles></PropertyGroup></Project>'
$script:CsGeneratedMapper = "namespace Demo;`npublic partial class Mapper { public partial int Map(int x); }`n" +
    "public static class Use { public static int Go() => new Mapper().Map(1); public static System.Func<int, int> F() => new Mapper().Map; }`n"
$script:CsGeneratedBody = "// <auto-generated/>`nnamespace Demo;`npublic partial class Mapper { public partial int Map(int x) => x + 1; }`n"
$script:CsGeneratedAt = 'obj/Debug/net10.0/generated/Fake.Gen/Fake.Gen.MapperGenerator/Mapper.g.cs'

function Invoke-CsGeneratedMap([string]$Tree) {
    $run = Invoke-Gate --root $Tree --skip 'bin,obj' --map-sqlite (Join-Path $Tree 'map.sqlite')
    Assert-Exit $run 0
    return $run
}

function Get-CsGeneratedNumber([string]$Tree, [string]$Sql) {
    $r = Invoke-Gate --map-query (Join-Path $Tree 'map.sqlite') --width 0 --sql $Sql
    Assert-Exit $r 0
    foreach ($line in $r.Lines) {
        $trimmed = $line.Trim()
        if ($trimmed.Length -gt 0 -and ($trimmed.ToCharArray() | Where-Object { -not [char]::IsDigit($_) }).Count -eq 0) { return $trimmed }
    }
    return ''
}

Test-Case 'generated: a partial a generator was going to write is labelled generator, not an error of the file' {
    $tree = Use-Tree @{ 'Demo.csproj' = $script:CsGeneratedProject; 'Mapper.cs' = $script:CsGeneratedMapper }
    $run = Invoke-CsGeneratedMap $tree
    Assert-Line $run "partial-method diagnostic(s) (CS8795/CS0762) are a source generator's missing output"
    Assert-Equal (Get-CsGeneratedNumber $tree "SELECT count(*) FROM diagnostics WHERE kind = 'generator'") '2' 'CS8795 and CS0762, labelled'
    Assert-Equal (Get-CsGeneratedNumber $tree "SELECT errors FROM files WHERE path = 'Mapper.cs'") '0' 'and not counted as errors'
}

Test-Case 'generated: what a generator emitted under obj/**/generated is compiled, never mapped' {
    $tree = Use-Tree @{ 'Demo.csproj' = $script:CsGeneratedProject; 'Mapper.cs' = $script:CsGeneratedMapper; $script:CsGeneratedAt = $script:CsGeneratedBody }
    $run = Invoke-CsGeneratedMap $tree
    Assert-NoLine $run 'partial-method diagnostic'
    Assert-Equal (Get-CsGeneratedNumber $tree "SELECT errors FROM files WHERE path = 'Mapper.cs'") '0' 'no error'
    Assert-Equal (Get-CsGeneratedNumber $tree "SELECT count(*) FROM files WHERE path LIKE '%generated%'") '0' 'the emitted file is not a mapped file'
}

Test-Case 'generated: a project that does not ask for emitted files has its obj never walked for them' {
    # THE SDK WRITES obj/**/generated ONLY WHEN ASKED: walking every project's obj for it was a cold run's seconds.
    $plain = '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>'
    $tree = Use-Tree @{ 'Demo.csproj' = $plain; 'Mapper.cs' = $script:CsGeneratedMapper; $script:CsGeneratedAt = $script:CsGeneratedBody }
    $run = Invoke-CsGeneratedMap $tree
    Assert-Line $run "partial-method diagnostic(s) (CS8795/CS0762) are a source generator's missing output"
}

Test-Case 'generated: a custom CompilerGeneratedFilesOutputPath is where the output is read' {
    # INSIDE THE PROJECT, so the project removes it from its own glob - as the SDK needs, or it compiles it twice.
    $project = $script:CsGeneratedProject.Replace('</PropertyGroup>', '<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath></PropertyGroup>' +
        '<ItemGroup><Compile Remove="Generated/**" /></ItemGroup>')
    $tree = Use-Tree @{ 'Demo.csproj' = $project; 'Mapper.cs' = $script:CsGeneratedMapper; 'Generated/Fake.Gen/Fake.Gen.MapperGenerator/Mapper.g.cs' = $script:CsGeneratedBody }
    $run = Invoke-Gate --root $tree --skip 'bin,obj,Generated' --map-sqlite (Join-Path $tree 'map.sqlite')
    Assert-Exit $run 0
    Assert-NoLine $run 'partial-method diagnostic'
}

Test-Case 'generated: the Razor generator''s output is not compiled beside the in-process Razor pass' {
    # A TYPE DECLARED TWICE leaves its uses unbound: the call below binds only while the copy stays out.
    $twin = 'obj/Debug/net10.0/generated/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Twin_razor.g.cs'
    $tree = Use-Tree @{ 'Demo.csproj' = $script:CsGeneratedProject; 'Twin.cs' = 'namespace Demo; public class Twin { public int M() => 1; }'
        'Use.cs' = 'namespace Demo; public class Use { public int Go() => new Twin().M(); }'
        $twin = "// <auto-generated/>`nnamespace Demo; public class Twin { public int M() => 1; }`n" }
    Invoke-CsGeneratedMap $tree | Out-Null
    Assert-Equal (Get-CsGeneratedNumber $tree "SELECT count(*) FROM calls WHERE symbol = 'Demo.Twin.M'") '1' 'the call bound to the one Twin'
}

Test-Case 'generated: output a build writes after a run re-reads the files, though no source moved' {
    $tree = Use-Tree @{ 'Demo.csproj' = $script:CsGeneratedProject; 'Mapper.cs' = $script:CsGeneratedMapper }
    Invoke-CsGeneratedMap $tree | Out-Null
    Assert-Equal (Get-CsGeneratedNumber $tree "SELECT count(*) FROM diagnostics WHERE kind = 'generator'") '2' 'before the build'
    $at = Join-Path $tree $script:CsGeneratedAt
    [void](New-Item -ItemType Directory -Path (Split-Path $at) -Force)
    [System.IO.File]::WriteAllText($at, $script:CsGeneratedBody)
    Invoke-CsGeneratedMap $tree | Out-Null
    Assert-Equal (Get-CsGeneratedNumber $tree "SELECT count(*) FROM diagnostics WHERE kind = 'generator'") '0' 'after it'
}

Test-Case 'generated: an output folder the project also globs is compiled once' {
    # INSIDE THE PROJECT AND NOT REMOVED: the walk compiles it as the project's own source, and the emitted list names it
    # again - twice, and the call into it stops binding.
    $project = $script:CsGeneratedProject.Replace('</PropertyGroup>', '<CompilerGeneratedFilesOutputPath>Gen</CompilerGeneratedFilesOutputPath></PropertyGroup>')
    $tree = Use-Tree @{ 'Demo.csproj' = $project; 'Gen/G/Helper.g.cs' = "// <auto-generated/>`nnamespace Demo;`npublic class Helper { public int M() => 1; }`n"
        'Use.cs' = 'namespace Demo; public class Use { public int Go() => new Helper().M(); }' }
    Assert-Exit (Invoke-Gate --root $tree --skip 'bin,obj,Gen' --map-sqlite (Join-Path $tree 'map.sqlite')) 0
    Assert-Equal (Get-CsGeneratedNumber $tree "SELECT count(*) FROM calls WHERE symbol = 'Demo.Helper.M'") '1' 'the call bound'
}
