<#
    The deep C# map, continued: GENERATED code (listed, never walked), `--map-sqlite` on its own, and
    the values the compiler will NOT fold, which this pass folds. Split from `CsRows` at its size limit.
#>

. (Join-Path $PSScriptRoot 'CsRows.Helpers.ps1')

# ---------------------------------------------------------------------------------------------------
# GENERATED CODE: listed, never walked - and a budget for whatever is generated without saying so
# ---------------------------------------------------------------------------------------------------

if ($script:CsRowsPython) {

Test-Case 'generated: a file that says it was generated is listed and NOT walked' {
    # Nobody asks which function reads a constant inside an EF model snapshot, and the rows are not free:
    # on one real tree nearly all of the expression rows came from `.Designer.cs` files and
    # writing them took hours. The file row stays, so the file has not silently vanished.
    $db = New-CsDb @{
        'Snapshot.cs' = '// <auto-generated />' + [char]10 +
                        'namespace Demo; public class Snapshot { public void Build() { Helper.Run("x"); } }'
        'Hand.cs'     = 'namespace Demo; public class Hand { public void Go() { Helper.Run("y"); } }'
    }
    Assert-Equal (Get-CsScalar $db "SELECT generated FROM files WHERE path = 'Snapshot.cs'") '1' 'marked generated'
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM calls c JOIN files f ON f.id = c.file WHERE f.path = 'Snapshot.cs'") '0' 'and not walked'
    # The hand-written file beside it is untouched by the rule.
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM calls c JOIN files f ON f.id = c.file WHERE f.path = 'Hand.cs'") '1' 'the authored file still has its rows'
}

Test-Case 'generated: the name conventions count too, marker or no marker' {
    $db = New-CsDb @{
        'Model.Designer.cs' = 'namespace Demo; public class Model { public void Build() { Helper.Run("x"); } }'
        'Parser.g.cs'       = 'namespace Demo; public class Parser { public void Build() { Helper.Run("x"); } }'
        # An authored file, so the `calls` table EXISTS to be asked about: a table that is missing entirely
        # fails the query rather than answering zero, and a case cannot tell those two apart.
        'Hand.cs'           = 'namespace Demo; public class Hand { public void Go() { Helper.Run("y"); } }'
    }
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM files WHERE generated = 1") '2' 'both named as generated'
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM calls c JOIN files f ON f.id = c.file WHERE f.path <> 'Hand.cs'") '0' 'neither was walked'
}

Test-Case 'generated: a folder called Migrations is NOT a generator' {
    # A folder name is a convention; a file somebody hand-wrote into it is still hand-written. The marker
    # the generator itself writes is the only thing this rule reads.
    $db = New-CsDb @{
        'Migrations/20240101_Init.cs' = 'namespace Demo; public class Init { public void Up() { Helper.Run("x"); } }'
    }
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM files WHERE generated = 1") '0' 'not generated'
    Assert-Equal (Get-CsScalar $db 'SELECT count(*) FROM calls') '1' 'and it was walked'
}

Test-Case 'budget: a large file is walked WHOLE - there is no per-file row budget' {
    # A budget once cut a file off at 20 000 rows, and the code past the cut could not be asked about.
    $lines = New-Object System.Text.StringBuilder
    [void]$lines.AppendLine('namespace Demo; public class Big { public void Go() {')
    for ($i = 1; $i -le 6000; $i++) { [void]$lines.AppendLine("var v$i = Helper.Run($i, $i + 1);") }
    [void]$lines.AppendLine('} }')
    $db = New-CsDb @{ 'Big.cs' = $lines.ToString() }
    # 6 000 calls, 6 000 assignments and 12 000 expressions: 24 000 rows, past the old 20 000, and the last
    # rows of the file are the ones a budget dropped.
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM calls c JOIN files f ON f.id = c.file WHERE f.path = 'Big.cs'") '6000' 'every call'
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM expressions x JOIN files f ON f.id = x.file WHERE f.path = 'Big.cs'") '12000' 'every expression'
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM assignments a JOIN files f ON f.id = a.file WHERE f.path = 'Big.cs'") '6000' 'every assignment'
    Assert-Equal (Get-CsScalar $db 'SELECT count(*) FROM (SELECT id FROM calls GROUP BY id HAVING count(*) > 1)') '0' 'no id handed out twice'
}

}

# ---------------------------------------------------------------------------------------------------
# --map-sqlite ON ITS OWN: the rows without the whole-tree re-parse the graph needs
# ---------------------------------------------------------------------------------------------------

if ($script:CsRowsPython) {

Test-Case 'deep only: --map-sqlite needs no --map, and writes no JSON map' {
    # The graph is a join over every name in the tree, so it re-reads all of it on every run: a turn that
    # changed one file paid minutes for a second of work. A per-turn hook runs this mode instead.
    $tree = Use-Tree @{ 'A.cs' = 'namespace Demo; public class A { public int Go() { return Helper.Run(1); } }' }
    $db = Join-Path $tree 'map.sqlite'
    $result = Invoke-Gate --root $tree --map-sqlite $db
    Assert-Exit $result 0
    Assert-Line $result 'database'
    if (-not (Test-Path $db)) { throw "no database was written. Output:`n$($result.Text)" }
    if (Test-Path (Join-Path $tree 'buildmap.json')) { throw 'a JSON map was written by a run that asked for none' }
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM calls WHERE callee = 'Helper.Run'") '1' 'the rows are there'
}

Test-Case 'deep only: the same tree yields the same rows as a run WITH the graph' {
    # `name.Length + 1` and not `name.Length`: a written-out name is deliberately not an expression row,
    # so the bare version produced no `expressions` table at all and the comparison had nothing to compare.
    $files = @{ 'A.cs' = 'namespace Demo; public class A { public int Go(string name) { return name.Length + 1; } }' }
    $withGraph = New-CsDb $files
    $rows = Get-CsScalar $withGraph 'SELECT count(*) FROM expressions'

    $tree = Use-Tree $files
    $db = Join-Path $tree 'map.sqlite'
    Assert-Exit (Invoke-Gate --root $tree --map-sqlite $db) 0
    Assert-Equal (Get-CsScalar $db 'SELECT count(*) FROM expressions') $rows 'the deep rows do not depend on the graph'
}

Test-Case 'deep only: a half that cannot run EXITS NON-ZERO, with no --map-check to ask for it' {
    # There is no graph here to report a finding against, so the exit code is the whole report: a database
    # that was not written is not a state anyone should have to notice for themselves.
    #
    # THE HALF IS BROKEN BY ITS STORE, not by its python. It used to be `--py-host no-such-python-here`,
    # because the C# rows were stored by `CsDb.py` in another process; they are now stored by fbtcore
    # inside this one, and a missing python says nothing about this half any more. A database that cannot
    # be opened is what it cannot survive today.
    $tree = Use-Tree @{ 'A.cs' = 'namespace Demo; public class A { public int Go() { return 1; } }' }
    $blocked = Join-Path $tree 'blocked'
    New-Item -ItemType Directory -Path $blocked | Out-Null
    $result = Invoke-Gate --root $tree --map-sqlite $blocked
    Assert-Exit $result 1
    Assert-Line $result 'cannot open the map database'
}

Test-Case 'deep only: the C# half maps a tree with no python on the machine at all' {
    # THE POINT OF THE MOVE. The rows are parsed by Roslyn in this process and stored by fbtcore in this
    # process, so the half owes nothing to a python interpreter. A consumer that has none still gets its
    # C# rows.
    $tree = Use-Tree @{ 'A.cs' = 'namespace Demo; public class A { public int Go() { return 1; } }' }
    $db = Join-Path $tree 'map.sqlite'
    $result = Invoke-Gate --root $tree --map-sqlite $db --py-host 'no-such-python-here'
    Assert-Exit $result 0
    Assert-NoLine $result 'did not run'
    if (-not (Test-Path $db)) { throw 'the database was not written' }

    # The receipt, not a lens: reading the rows back through --map-query would run a python lens and the
    # case would then need the very interpreter it is proving this half does without.
    Assert-Line $result '1 file(s) re-read'
}

Test-Case 'deep only: the flags that DO need --map still say so' {
    $tree = Use-Tree @{ 'A.cs' = 'namespace Demo; public class A { public int Go() { return 1; } }' }
    $result = Invoke-Gate --root $tree --map-sqlite (Join-Path $tree 'map.sqlite') --map-check
    Assert-Exit $result 2
    Assert-Line $result 'need --map'
}

}

# ---------------------------------------------------------------------------------------------------
# FOLDING, ENUMS AND RESOLVED REFERENCES: what the compiler will not fold for you
# ---------------------------------------------------------------------------------------------------

function Get-FoldingSample {
    return @'
namespace Demo;

public enum Region { EU = 1, US = 2 }

public static class Paths
{
    private static readonly string BaseUrl = Roots.Data + "/us";
    public const string Folder = "docs";

    public static string Doc(Region region, string name)
    {
        var built = $"{BaseUrl}/{Folder}/readme.pdf";
        var chosen = Region.US;
        var unknown = $"{name}/x.pdf";
        return Store.Save(built, chosen, unknown, Folder);
    }
}
'@
}

if ($script:CsRowsPython) {

Test-Case 'folded: an interpolated string is followed to its operands, across files' {
    # `GetConstantValue` answers only for compile-time constants, and a `static readonly` is not one - so
    # the row that somebody looking for this path would have found came back empty.
    $db = New-ProjectTree @{
        'Paths.cs' = Get-FoldingSample
        'Roots.cs' = 'namespace Demo; public static class Roots { public static readonly string Data = "/data"; }'
    }
    $r = Invoke-CsQ $db --sql "SELECT const, const_kind FROM assignments WHERE target = 'built'"
    Assert-Line $r '/data/us/docs/readme.pdf'
    # WHO FOLDED IT is recorded: the compiler could not, this pass did, and a reader is entitled to know
    # which of the two they are looking at.
    Assert-Line $r 'folded'
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM consts WHERE name = 'Folder' AND value_kind = 'const'") '1' 'a real constant still says const'
}

Test-Case 'folded: a piece that cannot be known folds to NOTHING, not to half a path' {
    # Half a path is worse than none, because it looks like a path.
    $db = New-ProjectTree @{
        'Paths.cs' = Get-FoldingSample
        'Roots.cs' = 'namespace Demo; public static class Roots { public static readonly string Data = "/data"; }'
    }
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM assignments WHERE target = 'unknown' AND const <> ''") '0' 'nothing claimed'
}

Test-Case 'enum: a member is a NAME, never the number it happens to be' {
    $db = New-ProjectTree @{
        'Paths.cs' = Get-FoldingSample
        'Roots.cs' = 'namespace Demo; public static class Roots { public static readonly string Data = "/data"; }'
    }
    $r = Invoke-CsQ $db --sql "SELECT const, const_kind FROM assignments WHERE target = 'chosen'"
    Assert-Line $r 'Demo.Region.US'
    Assert-Line $r 'enum'
    # `2` alone would be a row nobody can read back.
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM assignments WHERE target = 'chosen' AND const = '2'") '0' 'not the number'
}

Test-Case 'enum: a number that names no member says so, in a form nothing can mistake' {
    # A flags combination and a cast produce numbers that are not members. `Region=6` and `Region.US` differ
    # on sight, so a number can never be read as a member name.
    $db = New-ProjectTree @{
        'A.cs' = 'namespace Demo; public enum Region { EU = 1, US = 2 } public class A { public Region Odd = (Region)6; }'
    }
    Assert-Line (Invoke-CsQ $db --sql "SELECT const FROM assignments WHERE target = 'Odd'") 'Demo.Region=6'
}

Test-Case 'folded: a value that is not constant still says what it BINDS to' {
    $db = New-ProjectTree @{
        'Paths.cs' = Get-FoldingSample
        'Roots.cs' = 'namespace Demo; public static class Roots { public static readonly string Data = "/data"; }'
    }
    Assert-Line (Invoke-CsQ $db --sql "SELECT const_kind, symbol FROM arguments WHERE source = 'unknown'") 'unknown'
}

Test-Case 'refs: a reference to something THIS codebase declares is a row, resolved' {
    # `reads` is what the text says. This is what it means - the declaration it binds to - so "who touches
    # this field" is a query rather than a grep across two spellings of one name.
    $db = New-ProjectTree @{
        'Paths.cs' = Get-FoldingSample
        'Roots.cs' = 'namespace Demo; public static class Roots { public static readonly string Data = "/data"; }'
    }
    # TWO rows, because it is read on two lines: the dedup is per symbol per LINE, so a chain's own prefixes
    # collapse while two genuine reads stay two.
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM refs WHERE symbol = 'Demo.Paths.Folder'") '2' 'the const it reads, on both lines'
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM refs WHERE symbol = 'Demo.Roots.Data'") '1' 'and the one in the other file'
}

Test-Case 'refs: the framework, the locals and the callee of a call are NOT rows' {
    $db = New-ProjectTree @{
        'A.cs' = 'namespace Demo; public class A { public int Go(string name) { var n = name.Length; return Helper.Run(n); } }'
        'B.cs' = 'namespace Demo; public static class Helper { public static int Run(int n) { return n; } }'
    }
    # A reference to `string.Length` is a fact about the framework, not about this codebase.
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM refs WHERE symbol LIKE 'string.%' OR symbol LIKE 'System.%'") '0' 'no framework rows'
    # A local is named once and read three lines later; every one would be a row saying nothing.
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM refs WHERE name = 'n'") '0' 'no locals'
    # The callee already has a row of its own, with its arguments and its overload.
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM refs WHERE symbol = 'Demo.Helper.Run'") '0' 'the call row covers it'
    Assert-Equal (Get-CsScalar $db "SELECT count(*) FROM calls WHERE symbol = 'Demo.Helper.Run'") '1' 'and it is there'
}

}
