<#
    THE GO HALF (`rust/fbtcore/src/gomap/`): Go parsed INSIDE the exe by `gosyn`, for the gate's line count and the
    file map. A name belongs to its package, which is a folder: a plain name joins within the file's own folder, and
    `alias.Name` joins in the folder the import names through `go.mod` (or `vendor/`). A method reaches its file
    through its receiver type; build-constraint variants of one name are all targets; a `_test.go` declares nothing.

    Its helpers are its own - `-Only MapGo` runs this suite alone.
#>

$script:GoModule = "module example.com/demo`n`ngo 1.22`n"

# The map over $Tree's Go files, and the map it wrote.
function Invoke-GoMap([string]$Tree) {
    $result = Invoke-Gate --root $Tree --ext .go --map --map-check --map-out (Join-Path $Tree 'm.json')
    $map = [System.IO.File]::ReadAllText((Join-Path $Tree 'm.json')) | ConvertFrom-Json
    return [pscustomobject]@{ Result = $result; Map = $map }
}

function Get-GoImports($Map, [string]$Rel) {
    $listed = $Map.imports.$Rel
    if ($null -eq $listed) { return '' }
    return (@($listed) | Sort-Object) -join ','
}

Test-Case 'go: an aliased import joins the folder go.mod names, a method file through its type, and the tool chain''s entries' {
    $tree = Use-Tree @{
        'go.mod'                       = $script:GoModule
        'cmd/app/main.go'              = "package main`n`nimport (`n`t""fmt""`n`tst ""example.com/demo/internal/store""`n)`n`nfunc main() { fmt.Println(st.New().Load()) }`n"
        'internal/store/store.go'      = "package store`n`nimport ""example.com/demo/internal/util""`n`ntype Store struct{ n int }`n`nfunc New() Store { return Store{n: util.Double(2)} }`n"
        'internal/store/load.go'       = "package store`n`nfunc (s *Store) Load() int { return s.n }`n"
        'internal/store/store_test.go' = "package store`n`nimport ""testing""`n`nfunc TestNew(t *testing.T) { _ = New() }`n"
        'internal/util/util.go'        = "package util`n`nfunc Double[T ~int](v T) T { return v * 2 }`n"
        'internal/util/reg.go'         = "package util`n`nfunc init() { register() }`n`nfunc register() {}`n"
        'internal/util/gen.go'         = "// Code generated by tool. DO NOT EDIT.`n`npackage util`n`nconst Gen = 1`n"
        'internal/dead/dead.go'        = "package dead`n`nfunc Unused() int { return 1 }`n"
    }
    $run = Invoke-GoMap $tree
    Assert-Exit $run.Result 0
    Assert-Line $run.Result 'go in-process (gosyn)'
    Assert-Equal (Get-GoImports $run.Map 'cmd/app/main.go') 'internal/store/store.go' 'through the alias st'
    # THE METHOD FILE THROUGH ITS TYPE: `store.go` names `Store`, whose `Load` lives in `load.go`.
    Assert-Equal (Get-GoImports $run.Map 'internal/store/store.go') 'internal/store/load.go,internal/util/util.go' 'the method file, and a generic function through its import'
    Assert-Equal $run.Map.files.'cmd/app/main.go'.entry $true 'package main with func main'
    Assert-Equal $run.Map.files.'internal/store/store_test.go'.entry $true 'a test file'
    Assert-Equal ((@($run.Map.files.'internal/util/reg.go'.registered)) -join ',') 'init' 'a file with init'
    Assert-Equal $run.Map.files.'internal/util/gen.go'.generated $true 'the generated marker'
    Assert-Line $run.Result 'NO READER internal/dead/dead.go'
    Assert-NoLine $run.Result 'NO READER internal/store/load.go'
}

Test-Case 'go: two packages that declare one name never meet, and a test file declares nothing' {
    $tree = Use-Tree @{
        'go.mod'       = $script:GoModule
        'a/a.go'       = "package a`n`nfunc New() int { return 1 }`n"
        'b/b.go'       = "package b`n`nfunc New() int { return 2 }`n"
        'b/b_test.go'  = "package b`n`nfunc helper() int { return 3 }`n"
        'b/use.go'     = "package b`n`nfunc Use() int { return helper() }`n"
        'c/c.go'       = "package c`n`nimport ""example.com/demo/a""`n`nfunc Go() int { return a.New() }`n"
    }
    $run = Invoke-GoMap $tree
    Assert-Equal (Get-GoImports $run.Map 'c/c.go') 'a/a.go' 'only the package the import names'
    Assert-Equal (Get-GoImports $run.Map 'b/use.go') '' 'not a name only the test build declares'
    Assert-NoLine $run.Result 'AMBIGUOUS'
}

Test-Case 'go: build-constraint variants of one name are all targets, and a vendored import resolves' {
    $tree = Use-Tree @{
        'go.mod'                              = $script:GoModule
        'sys/open_linux.go'                   = "//go:build linux`n`npackage sys`n`nfunc Open() int { return 1 }`n"
        'sys/open_windows.go'                 = "//go:build windows`n`npackage sys`n`nfunc Open() int { return 2 }`n"
        'sys/use.go'                          = "package sys`n`nimport ""golang.org/x/lib""`n`nfunc Use() int { return Open() + lib.Value }`n"
        'vendor/golang.org/x/lib/lib.go'      = "package lib`n`nconst Value = 3`n"
    }
    $run = Invoke-GoMap $tree
    Assert-Equal (Get-GoImports $run.Map 'sys/use.go') 'sys/open_linux.go,sys/open_windows.go,vendor/golang.org/x/lib/lib.go' 'both variants and the vendored copy'
    Assert-NoLine $run.Result 'AMBIGUOUS'
}

Test-Case 'go: the gate counts Go by its lexer, as the map does, and a file that does not parse is named with its line' {
    $tree = Use-Tree @{
        'go.mod'  = $script:GoModule
        'raw.go'  = "// header`npackage raw`n`n/* block`n   comment */`nvar S = ```n// not a comment```n"
        'bad.go'  = "package raw`n`nfunc Broken( {`n}`n"
    }
    # A RAW STRING HOLDING A `//` LINE IS CODE: three source lines, where a `//` scanner counts two.
    $gate = Invoke-Gate --root $tree --ext .go --max-lines 2
    Assert-Exit $gate 1
    Assert-Line $gate '3  raw.go'
    $run = Invoke-GoMap $tree
    Assert-Equal $run.Map.files.'raw.go'.lines 3 'the map agrees'
    Assert-Line $run.Result 'UNPARSED  bad.go:3:'
}
